# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocfl/v1/index.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ocfl/v1/index.proto", :syntax => :proto3) do
    add_message "ocfl.v1.GetStatusRequest" do
    end
    add_message "ocfl.v1.GetStatusResponse" do
      optional :status, :string, 1, json_name: "status"
      optional :store_root_path, :string, 2, json_name: "storeRootPath"
      optional :store_spec, :string, 3, json_name: "storeSpec"
      optional :store_description, :string, 4, json_name: "storeDescription"
      optional :num_object_paths, :int32, 5, json_name: "numObjectPaths"
      optional :num_inventories, :int32, 6, json_name: "numInventories"
    end
    add_message "ocfl.v1.IndexAllRequest" do
    end
    add_message "ocfl.v1.IndexAllResponse" do
    end
    add_message "ocfl.v1.IndexIDsRequest" do
      repeated :object_ids, :string, 1, json_name: "objectIds"
    end
    add_message "ocfl.v1.IndexIDsResponse" do
    end
    add_message "ocfl.v1.ListObjectsRequest" do
      optional :page_token, :string, 1, json_name: "pageToken"
      optional :page_size, :int32, 2, json_name: "pageSize"
      optional :id_prefix, :string, 3, json_name: "idPrefix"
    end
    add_message "ocfl.v1.ListObjectsResponse" do
      repeated :objects, :message, 1, "ocfl.v1.ListObjectsResponse.Object", json_name: "objects"
      optional :next_page_token, :string, 2, json_name: "nextPageToken"
    end
    add_message "ocfl.v1.ListObjectsResponse.Object" do
      optional :object_id, :string, 1, json_name: "objectId"
      optional :head, :string, 2, json_name: "head"
      optional :v1_created, :message, 3, "google.protobuf.Timestamp", json_name: "v1Created"
      optional :head_created, :message, 4, "google.protobuf.Timestamp", json_name: "headCreated"
    end
    add_message "ocfl.v1.GetObjectRequest" do
      optional :object_id, :string, 1, json_name: "objectId"
    end
    add_message "ocfl.v1.GetObjectResponse" do
      optional :object_id, :string, 1, json_name: "objectId"
      optional :spec, :string, 2, json_name: "spec"
      optional :root_path, :string, 3, json_name: "rootPath"
      optional :digest_algorithm, :string, 4, json_name: "digestAlgorithm"
      repeated :versions, :message, 5, "ocfl.v1.GetObjectResponse.Version", json_name: "versions"
      optional :indexed_at, :message, 6, "google.protobuf.Timestamp", json_name: "indexedAt"
    end
    add_message "ocfl.v1.GetObjectResponse.Version" do
      optional :num, :string, 1, json_name: "num"
      optional :message, :string, 2, json_name: "message"
      optional :created, :message, 3, "google.protobuf.Timestamp", json_name: "created"
      proto3_optional :user, :message, 4, "ocfl.v1.GetObjectResponse.Version.User", json_name: "user"
      optional :size, :int64, 5, json_name: "size"
      optional :has_size, :bool, 6, json_name: "hasSize"
    end
    add_message "ocfl.v1.GetObjectResponse.Version.User" do
      optional :name, :string, 1, json_name: "name"
      optional :address, :string, 2, json_name: "address"
    end
    add_message "ocfl.v1.GetObjectStateRequest" do
      optional :object_id, :string, 1, json_name: "objectId"
      optional :version, :string, 2, json_name: "version"
      optional :base_path, :string, 3, json_name: "basePath"
      optional :recursive, :bool, 4, json_name: "recursive"
      optional :page_token, :string, 5, json_name: "pageToken"
      optional :page_size, :int32, 6, json_name: "pageSize"
    end
    add_message "ocfl.v1.GetObjectStateResponse" do
      optional :digest, :string, 1, json_name: "digest"
      optional :isdir, :bool, 2, json_name: "isdir"
      optional :size, :int64, 3, json_name: "size"
      optional :has_size, :bool, 4, json_name: "hasSize"
      repeated :children, :message, 5, "ocfl.v1.GetObjectStateResponse.Item", json_name: "children"
      optional :next_page_token, :string, 6, json_name: "nextPageToken"
    end
    add_message "ocfl.v1.GetObjectStateResponse.Item" do
      optional :name, :string, 1, json_name: "name"
      optional :isdir, :bool, 2, json_name: "isdir"
      optional :size, :int64, 3, json_name: "size"
      optional :has_size, :bool, 4, json_name: "hasSize"
      optional :digest, :string, 5, json_name: "digest"
    end
    add_message "ocfl.v1.FollowLogsRequest" do
    end
    add_message "ocfl.v1.FollowLogsResponse" do
      optional :message, :string, 1, json_name: "message"
    end
  end
end

module Ocfl
  module V1
    GetStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.GetStatusRequest").msgclass
    GetStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.GetStatusResponse").msgclass
    IndexAllRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.IndexAllRequest").msgclass
    IndexAllResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.IndexAllResponse").msgclass
    IndexIDsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.IndexIDsRequest").msgclass
    IndexIDsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.IndexIDsResponse").msgclass
    ListObjectsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.ListObjectsRequest").msgclass
    ListObjectsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.ListObjectsResponse").msgclass
    ListObjectsResponse::Object = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.ListObjectsResponse.Object").msgclass
    GetObjectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.GetObjectRequest").msgclass
    GetObjectResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.GetObjectResponse").msgclass
    GetObjectResponse::Version = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.GetObjectResponse.Version").msgclass
    GetObjectResponse::Version::User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.GetObjectResponse.Version.User").msgclass
    GetObjectStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.GetObjectStateRequest").msgclass
    GetObjectStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.GetObjectStateResponse").msgclass
    GetObjectStateResponse::Item = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.GetObjectStateResponse.Item").msgclass
    FollowLogsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.FollowLogsRequest").msgclass
    FollowLogsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ocfl.v1.FollowLogsResponse").msgclass
  end
end
