before:
  hooks:
    - go mod tidy
    - go mod download
    - buf generate api
    - sqlc generate -f internal/sqlite/sqlc.yaml 
    - go test -v ./...
builds: 
  - binary: ocfl-index
    main: ./cmd/ocfl-index
    env:
      - CGO_ENABLED=0
    targets:
      - "linux_amd64"
      - "darwin_arm64"
      - "windows_amd64"
    flags:
      - -tags=netgo
    ldflags:
      - -s -w -X 'github.com/srerickson/ocfl-index/internal/index.Version={{.Version}}' -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
  - id: "ox"
    binary: ox
    main: ./cmd/ox
    env:
      - CGO_ENABLED=0
    targets:
      - "linux_amd64"
      - "darwin_arm64"
      - "windows_amd64"
    flags:
      - -tags=netgo
    ldflags:
      - -s -w -X 'github.com/srerickson/ocfl-index/internal/index.Version={{.Version}}' -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
archives:
  - format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^testdata:'
dockers:
  - dockerfile: Dockerfile.goreleaser
    skip_push: true
    image_templates:
      - "srerickson/ocfl-index:latest"
      - "srerickson/ocfl-index:{{ .Tag }}"