// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"
	"time"
)

type OcflIndexContentPath struct {
	InventoryID int64
	NodeID      int64
	FilePath    string
}

type OcflIndexInventory struct {
	ID              int64
	RootID          int64
	OcflID          string
	Spec            string
	DigestAlgorithm string
	InventoryDigest string
	Head            string
	IndexedAt       time.Time
}

type OcflIndexName struct {
	Name     string
	NodeID   int64
	ParentID int64
}

type OcflIndexNode struct {
	ID   int64
	Dir  bool
	Sum  []byte
	Size sql.NullInt64
}

type OcflIndexObjectRoot struct {
	ID        int64
	Path      string
	IndexedAt time.Time
}

type OcflIndexSchema struct {
	Major int64
	Minor int64
}

type OcflIndexStorageRoot struct {
	ID   int64
	Name string
}

type OcflIndexVersion struct {
	InventoryID int64
	Num         int64
	Name        string
	Message     string
	Created     time.Time
	UserName    string
	UserAddress string
	NodeID      int64
}
