// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"
)

type OcflIndexContentPath struct {
	ObjectID int64
	NodeID   int64
	FilePath string
}

type OcflIndexName struct {
	NodeID   int64
	Name     string
	ParentID int64
}

type OcflIndexNode struct {
	ID   int64
	Dir  bool
	Sum  []byte
	Size int64
}

type OcflIndexObject struct {
	ID              int64
	OcflID          string
	Spec            string
	DigestAlgorithm string
	InventoryDigest string
	RootPath        string
	Head            string
}

type OcflIndexObjectVersion struct {
	ObjectID    int64
	Num         int64
	Name        string
	Message     string
	Created     time.Time
	UserName    string
	UserAddress string
	NodeID      int64
}

type OcflIndexSchema struct {
	Major int64
	Minor int64
}

type OcflIndexStorageRoot struct {
	ID          int64
	RootPath    string
	Description string
	Spec        string
	IndexedAt   sql.NullTime
}
