// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlc

import (
	"time"
)

type OcflIndexContentPath struct {
	ObjectID int64
	NodeID   int64
	FilePath string
}

type OcflIndexName struct {
	NodeID   int64
	Name     string
	ParentID int64
}

type OcflIndexNode struct {
	ID  int64
	Dir bool
	Sum []byte
}

type OcflIndexObject struct {
	ID     int64
	Uri    string
	Head   string
	NodeID int64
}

type OcflIndexObjectVersion struct {
	ObjectID    int64
	Num         int64
	Name        string
	Message     string
	Created     time.Time
	UserName    string
	UserAddress string
}

type OcflIndexSchema struct {
	Major int64
	Minor int64
}
